name: Build for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.platform }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - platform: Windows
            target_platform: WINDOWS
            arch: x86_64
            runs-on: windows-latest
            toolchain: x86_64-w64-mingw32
          - platform: Windows
            target_platform: WINDOWS
            arch: i686
            runs-on: windows-latest
            toolchain: i686-w64-mingw32
          - platform: Windows
            target_platform: WINDOWS
            arch: arm64
            runs-on: windows-latest
            toolchain: aarch64-w64-mingw32

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
        # Expose Dart SDK path for later steps
        env:
          DART_HOME: ${{ steps.setup-dart.outputs.dart-sdk-path }}

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29'

      - name: Install Ninja
        run: |
          choco install ninja -y
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

      - name: Install dependencies (Windows)
        shell: powershell
        run: |
          choco install mingw --version 8.1.0 -y
          $llvmMingwUrl = "https://github.com/mstorsjo/llvm-mingw/releases/download/20231004/llvm-mingw-20231004-ucrt-x86_64.zip"
          Invoke-WebRequest -Uri $llvmMingwUrl -OutFile llvm-mingw.zip
          Expand-Archive -Path llvm-mingw.zip -DestinationPath llvm-mingw
          echo "$pwd\llvm-mingw\bin" >> $env:GITHUB_PATH
          
      - name: Configure Windows CMake
        shell: bash
        run: |
          if [ "${{ matrix.arch }}" = "arm64" ]; then
            export CC="aarch64-w64-mingw32-gcc"
          elif [ "${{ matrix.arch }}" = "i686" ]; then
            export CC="i686-w64-mingw32-gcc"
          else
            export CC="x86_64-w64-mingw32-gcc"
          fi

          cmake \
            -G 'Ninja' \
            -DTARGET_PLATFORM=${{ matrix.target_platform }} \
            -DTARGET_ARCH=${{ matrix.arch }} \
            -DDART_SDK_PATH="${{ env.DART_HOME || '/usr/lib/dart' }}" \
            -DCMAKE_C_COMPILER=$CC \
            .
          
      - name: Build
        shell: bash
        run: |
          ninja

      - name: Verify Windows DLL architecture
        shell: bash
        run: |
          objdump -f libs/libWatcherPlus_${{ matrix.arch }}.dll | grep "file format"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WatcherPlus-${{ matrix.platform }}-${{ matrix.arch }}
          path: libs/libWatcherPlus_${{ matrix.arch }}.*
