name: Build WatcherPlus for All Platforms and Architectures

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.platform }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - platform: macOS
            target_platform: NATIVE
            arch: arm64
            runs-on: macos-latest
          - platform: macOS
            target_platform: NATIVE
            arch: x86_64
            runs-on: macos-latest
          - platform: Windows
            target_platform: WINDOWS
            arch: x86_64
            runs-on: windows-latest
          - platform: Windows
            target_platform: WINDOWS
            arch: arm64
            runs-on: windows-latest
          - platform: Windows
            target_platform: WINDOWS
            arch: i686
            runs-on: windows-latest
          - platform: Linux
            target_platform: LINUX
            arch: x86_64
            runs-on: ubuntu-latest
          - platform: Linux
            target_platform: LINUX
            arch: arm64
            runs-on: ubuntu-latest
          - platform: Linux
            target_platform: LINUX
            arch: i686
            runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart
        id: setup-dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
        env:
          DART_HOME: ${{ steps.setup-dart.outputs.dart-sdk-path }}

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29'

      - name: Install Ninja
        if: matrix.platform == 'Windows' || matrix.platform == 'Linux'
        run: |
          if [ "${{ matrix.platform }}" = "Windows" ]; then
            choco install ninja -y
            echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH
          else
            sudo apt-get update
            sudo apt-get install -y ninja-build
          fi

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macOS'
        run: |
          brew install coreutils

      - name: Install dependencies (Windows)
        if: matrix.platform == 'Windows'
        shell: bash
        run: |
          choco install msys2 -y
          echo "C:\tools\msys64\mingw64\bin" >> $GITHUB_PATH
          echo "C:\tools\msys64\usr\bin" >> $GITHUB_PATH
          pacman -S --noconfirm mingw-w64-x86_64-gcc
          pacman -S --noconfirm mingw-w64-aarch64-gcc
          pacman -S --noconfirm mingw-w64-i686-gcc

      - name: Install dependencies (Linux)
        if: matrix.platform == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc g++ gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-i686-linux-gnu g++-i686-linux-gnu

      - name: Debug Compilers
        shell: bash
        run: |
          if [ "${{ matrix.platform }}" = "Windows" ]; then
            x86_64-w64-mingw32-gcc --version || echo "x86_64 compiler missing"
            aarch64-w64-mingw32-gcc --version || echo "ARM64 compiler missing"
            i686-w64-mingw32-gcc --version || echo "x86 compiler missing"
          elif [ "${{ matrix.platform }}" = "Linux" ]; then
            gcc --version || echo "gcc missing"
            aarch64-linux-gnu-gcc --version || echo "ARM64 compiler missing"
            i686-linux-gnu-gcc --version || echo "x86 compiler missing"
          else
            cc --version || echo "macOS compiler missing"
          fi

      - name: Configure macOS CMake
        shell: bash
        if: matrix.platform == 'macOS'
        run: |
          cmake \
            -G 'Unix Makefiles' \
            -DTARGET_PLATFORM=${{ matrix.target_platform }} \
            -DTARGET_ARCH=${{ matrix.arch }} \
            -DDART_SDK_PATH="${{ env.DART_HOME || '/usr/lib/dart' }}" \
            . || { echo "CMake failed for macOS"; cat CMakeFiles/CMakeError.log; exit 1; }
        env:
          DART_HOME: ${{ env.DART_HOME }}

      - name: Configure Windows CMake
        shell: bash
        if: matrix.platform == 'Windows'
        run: |
          cmake \
            -G 'Ninja' \
            -DTARGET_PLATFORM=${{ matrix.target_platform }} \
            -DTARGET_ARCH=${{ matrix.arch }} \
            -DDART_SDK_PATH="${{ env.DART_HOME || '/usr/lib/dart' }}" \
            -DCMAKE_C_COMPILER=${{ matrix.arch == 'x86_64' && 'x86_64-w64-mingw32-gcc' || matrix.arch == 'arm64' && 'aarch64-w64-mingw32-gcc' || 'i686-w64-mingw32-gcc' }} \
            . || { echo "CMake failed for Windows"; cat CMakeFiles/CMakeError.log; exit 1; }
        env:
          DART_HOME: ${{ env.DART_HOME }}

      - name: Configure Linux CMake
        shell: bash
        if: matrix.platform == 'Linux'
        run: |
          cmake \
            -G 'Ninja' \
            -DTARGET_PLATFORM=${{ matrix.target_platform }} \
            -DTARGET_ARCH=${{ matrix.arch }} \
            -DDART_SDK_PATH="${{ env.DART_HOME || '/usr/lib/dart' }}" \
            -DCMAKE_C_COMPILER=${{ matrix.arch == 'x86_64' && 'gcc' || matrix.arch == 'arm64' && 'aarch64-linux-gnu-gcc' || 'i686-linux-gnu-gcc' }} \
            . || { echo "CMake failed for Linux"; cat CMakeFiles/CMakeError.log; exit 1; }
        env:
          DART_HOME: ${{ env.DART_HOME }}


      - name: Build
        shell: bash
        run: |
          ${{ matrix.platform == 'macOS' && 'make' || 'ninja' }}

      - name: Verify macOS dylib architecture
        if: matrix.platform == 'macOS'
        run: |
          file libs/libWatcherPlus_${{ matrix.arch }}.dylib

      - name: Verify Windows DLL architecture
        if: matrix.platform == 'Windows'
        shell: bash
        run: |
          objdump -f libs/libWatcherPlus_${{ matrix.arch }}.dll | grep "file format"

      - name: Verify Linux library architecture
        if: matrix.platform == 'Linux'
        run: |
          file libs/libWatcherPlus_${{ matrix.arch }}.so

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WatcherPlus-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            libs/libWatcherPlus_${{ matrix.arch }}.dylib
            libs/libWatcherPlus_${{ matrix.arch }}.dll
            libs/libWatcherPlus_${{ matrix.arch }}.so
