name: Build WatcherPlus for All Platforms and Architectures

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.platform }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - platform: macOS
            target_platform: NATIVE
            arch: arm64
            runs-on: macos-latest
          - platform: macOS
            target_platform: NATIVE
            arch: x86_64
            runs-on: macos-latest
          - platform: Windows
            target_platform: WINDOWS
            arch: x86_64
            runs-on: windows-latest
          - platform: Windows
            target_platform: WINDOWS
            arch: arm64
            runs-on: windows-latest
          - platform: Windows
            target_platform: WINDOWS
            arch: i686
            runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
        env:
          DART_HOME: ${{ steps.setup-dart.outputs.dart-sdk-path }}

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29'

      - name: Install Ninja
        if: matrix.platform == 'Windows'
        run: |
          choco install ninja -y
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macOS'
        run: |
          brew install coreutils

      - name: Install dependencies (Windows)
        if: matrix.platform == 'Windows'
        run: |
          choco install mingw --version 8.1.0 -y
          echo "C:\ProgramData\mingw64\native\mingw64\bin" >> $GITHUB_PATH

      - name: Debug Directory Contents
        run: |
          ls -la

      - name: Configure macOS CMake
        shell: bash
        if: matrix.platform == 'macOS'
        run: |
          cmake \
            -DTARGET_PLATFORM=${{ matrix.target_platform }} \
            -DTARGET_ARCH=${{ matrix.arch }} \
            -DDART_SDK_PATH="${{ env.DART_HOME || '/usr/lib/dart' }}" \
            .
        env:
          DART_HOME: ${{ env.DART_HOME }}

      - name: Configure Windows CMake
        shell: bash
        if: matrix.platform == 'Windows'
        run: |
          cmake \
            -G 'Ninja' \
            -DTARGET_PLATFORM=${{ matrix.target_platform }} \
            -DTARGET_ARCH=${{ matrix.arch }} \
            -DDART_SDK_PATH="${{ env.DART_HOME || '/usr/lib/dart' }}" \
            -DCMAKE_C_COMPILER=${{ matrix.arch == 'x86_64' && 'x86_64-w64-mingw32-gcc' || matrix.arch == 'arm64' && 'aarch64-w64-mingw32-gcc' || 'i686-w64-mingw32-gcc' }} \
            .
        env:
          DART_HOME: ${{ env.DART_HOME }}

      - name: Build
        shell: bash
        run: |
          ${{ matrix.platform == 'Windows' && 'ninja' || 'make' }}

      - name: Verify macOS dylib architecture
        if: matrix.platform == 'macOS'
        run: |
          file libs/libWatcherPlus_${{ matrix.arch }}.dylib

      - name: Verify Windows DLL architecture
        if: matrix.platform == 'Windows'
        shell: bash
        run: |
          objdump -f libs/libWatcherPlus_${{ matrix.arch }}.dll | grep "file format"

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WatcherPlus-${{ matrix.platform }}-${{ matrix.arch }}
          path: libs/libWatcherPlus_${{ matrix.arch }}.*
