name: Build WatcherPlus for All Platforms and Architectures

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.platform }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
          - platform: macOS
            target_platform: NATIVE
            arch: arm64
            runs-on: macos-latest
          - platform: macOS
            target_platform: NATIVE
            arch: x86_64
            runs-on: macos-latest
          - platform: Windows
            target_platform: NATIVE
            arch: x86_64
            runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29'

      - name: Install dependencies (macOS)
        if: matrix.platform == 'macOS'
        run: |
          brew install coreutils

      - name: Install dependencies (Windows)
        if: matrix.platform == 'Windows'
        run: |
          choco install mingw --version 8.1.0 -y
          echo "C:\ProgramData\mingw64\mingw64\bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          cmake \
            -DTARGET_PLATFORM=${{ matrix.target_platform }} \
            -DTARGET_ARCH=${{ matrix.arch }} \
            -DDART_SDK_PATH=$DART_HOME \
            ${{ matrix.platform == 'Windows' && '-G "MinGW Makefiles"' || '' }}
        env:
          DART_HOME: ${{ env.DART_HOME || '/usr/lib/dart' }}

      - name: Build
        run: |
          ${{ matrix.platform == 'Windows' && 'mingw32-make' || 'make' }}

      - name: Verify macOS dylib architecture
        if: matrix.platform == 'macOS'
        run: |
          file libs/libWatcherPlus_${{ matrix.arch }}.dylib

      - name: Verify Windows DLL architecture
        if: matrix.platform == 'Windows'
        run: |
          dumpbin /headers libs/libWatcherPlus_${{ matrix.arch }}.dll | findstr machine

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WatcherPlus-${{ matrix.platform }}-${{ matrix.arch }}
          path: libs/libWatcherPlus_${{ matrix.arch }}.*
